name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche le déploiement quand tu pushes sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy public folder to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # <-- Ici c'est ton dossier "public"
